name: pytcu11
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.7.22
  - cachetools=4.2.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - cryptography=41.0.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cytoolz=0.12.0
  - dask-core=2023.6.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - flatbuffers=2.0.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - gast=0.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.5.2
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - importlib-metadata=6.0.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jxrlib=1.1
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcurl=8.1.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - lightning-utilities=0.9.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - monai=1.2.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - nibabel=5.1.0
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1v
  - opt_einsum=3.3.0
  - packaging=23.0
  - partd=1.2.0
  - pillow=9.4.0
  - pip=23.2.1
  - pluggy=1.0.0
  - pooch=1.4.0
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.11.4
  - python-flatbuffers=2.0
  - python_abi=3.11
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-model-summary=0.1.1
  - pytorch-mutex=1.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.12.0
  - tensorflow-base=2.12.0
  - tensorflow-estimator=2.12.0
  - termcolor=2.1.0
  - threadpoolctl=3.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.12.0
  - torchmetrics=1.0.3
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tqdm=4.65.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - werkzeug=2.2.3
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - jax==0.4.14
      - libclang==16.0.6
      - ml-dtypes==0.2.0
      - tensorboard-plugin-3d==1.0.3
      - tensorflow-io-gcs-filesystem==0.33.0
      - torchsummary==1.5.1
